### ISSUE TITLE
Buffer Underflow

### ISSUE THREAD

**Issue by TheJavaHacker** [hollow-cube/schem#6]
I'm not sure what kind of buffoon I'm being, but I keep getting a BufferUnderflowException when I'm using this library, no matter what schematic I use.

I am using the .schematic file type, because when I convert to .schem file, the library absolutely refuses to understand it.
The .schematic file is 30KB, and I'm following several of the examples found in the Minestom Discord and in the test directory of this repo.

The code:

```
try (var is = getClass().getResourceAsStream("/FloatingSpawn.schematic")) {
            assert is != null;
            var schem = new SchematicReader().read(is);
            schem.build(Rotation.NONE, false).apply(overworld, new Pos(0.500, 100, 0.500), () -> {
                System.out.println("Schematic Pasted.");
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
```

The error:

```
java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:713)
	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:172)
	at net.minestom.server.utils.Utils.readVarInt(Utils.java:52)
	at net.hollowcube.schem.Schematic.apply(Schematic.java:68)
	at net.hollowcube.schem.Schematic.build(Schematic.java:98)
	at org.infinitegaming.Core.<init>(Core.java:99)
	at org.infinitegaming.Core.main(Core.java:70)
```
	
I've tried using multiple schematic files, to no avail.
Is it something really obvious I'm missing? I tend to do that.

Thanks in Advance.

**Comment by TheJavaHacker** [comment]
Well I'm just a fucking idiot. Sorry <3.
